import type { BuildingDef, BuildingId } from './types';

export const BUILDINGS: Record<BuildingId, BuildingDef> = {
  house: {
    id: 'house',
    name: 'Дом',
    description: 'Даёт жильё для жителей. Больше домов — больше населения.',
    cost: { materials: 12 },
    produces: {},
    upkeep: {},
    housing: 4,
    category: 'housing',
    buildableOn: ['grass', 'sand', 'forest'],
  },
  farm: {
    id: 'farm',
    name: 'Ферма',
    description: 'Выращивает еду для жителей поселения.',
    cost: { materials: 10 },
    produces: { food: 6 },
    upkeep: {},
    housing: 0,
    category: 'production',
    buildableOn: ['grass', 'sand'],
  },
  sawmill: {
    id: 'sawmill',
    name: 'Лесопилка',
    description: 'Заготавливает древесину. Рядом с лесом работает лучше.',
    cost: { materials: 8, gold: 5 },
    produces: { materials: 5 },
    upkeep: {},
    housing: 0,
    bonusTerrain: 'forest',
    bonusMultiplier: 1.6,
    category: 'production',
    buildableOn: ['grass', 'forest'],
  },
  quarry: {
    id: 'quarry',
    name: 'Каменоломня',
    description: 'Добывает камень. На каменистой почве продуктивнее.',
    cost: { materials: 14 },
    produces: { materials: 5 },
    upkeep: {},
    housing: 0,
    bonusTerrain: 'rock',
    bonusMultiplier: 1.6,
    category: 'production',
    buildableOn: ['grass', 'rock'],
  },
  market: {
    id: 'market',
    name: 'Рынок',
    description: 'Продаёт излишки и приносит золото от торговли.',
    cost: { materials: 16, gold: 5 },
    produces: { gold: 5 },
    upkeep: {},
    housing: 0,
    category: 'commerce',
    buildableOn: ['grass', 'sand'],
  },
  well: {
    id: 'well',
    name: 'Колодец',
    description: 'Чистая вода радует жителей — население растёт охотнее.',
    cost: { materials: 6 },
    produces: {},
    upkeep: {},
    housing: 0,
    category: 'decorative',
    buildableOn: ['grass', 'sand', 'forest', 'rock'],
  },
  tavern: {
    id: 'tavern',
    name: 'Таверна',
    description: 'Место отдыха жителей. Приносит немного золота и радости.',
    cost: { materials: 18, gold: 8 },
    produces: { gold: 4 },
    upkeep: { food: 1 },
    housing: 0,
    category: 'commerce',
    buildableOn: ['grass', 'sand'],
  },
  lighthouse: {
    id: 'lighthouse',
    name: 'Маяк',
    description: 'Особое здание побережья. Привлекает торговые караваны.',
    cost: { materials: 30, gold: 20 },
    produces: { gold: 3 },
    upkeep: {},
    housing: 0,
    category: 'decorative',
    buildableOn: ['sand'],
  },
};

export const BUILDING_ORDER: BuildingId[] = [
  'house',
  'farm',
  'sawmill',
  'quarry',
  'market',
  'well',
  'tavern',
  'lighthouse',
];
